seed: 42
bar_interval: '3min'
universe:
  - RELIANCE.NS
  - HDFCBANK.NS
  - TCS.NS
  - NIFTY_FUT
  - BANKNIFTY_FUT

label:
  horizon_bars: 8         # ~24 minutes
  tp_multiple: 0.75
  sl_multiple: 0.5

features:
  rsi_period: 7
  atr_period: 14
  vwap_window: 50
  zscore_window: 50

cv:
  n_splits: 5
  embargo_bars: 8
  purge_gap_bars: 8

risk:
  capital_inr: 60000
  per_trade_risk_frac: 0.0035    # ~₹210 risk/trade
  daily_loss_stop_frac: 0.01     # ~₹600/day

costs:
  brokerage_bps: 1.0
  stt_bps: 10.0
  slippage_bps: 2.0
  exchange_fees_bps: 0.5

paper_trading:
  mode: "replay"      # "live" later
  starting_capital_inr: 60000
  daily_loss_stop_inr: 600
  per_trade_risk_inr: 210
  bar_interval_sec: 180
  skip_minutes:
    pre_open: 9
    pre_close: 10
  replay:
    date: "2025-08-12"
